# A generic, single database configuration.

[alembic]
# path to migration scripts
script_location = alembic

# template used to generate migration file names; The default version attrs are used
# file_template = %%(year)d_%%(month).2d_%%(day).2d_%%(hour).2d%%(minute).2d-%%(rev)s_%%(slug)s

# sys.path path, separated by systems path separator.
# This path is prepended to sys.path when running alembic.
prepend_syspath = .

# timezone to use when rendering the date within the migration file
# timezone =

# max length of characters to prepend to the "slug" in the migration filename
# truncate_slug_length = 40

# set to 'true' to run the environment during
# the 'revision' command, regardless of autogenerate
# revision_environment = false

# set to 'true' to allow modules to be imported by their relative path
# within the version scripts
# allow_relative_imports = false

# version locations.  specifies where version files are located.
# defaults to alembic/versions
# version_locations = %(here)s/alembic/versions

# version_path_separator = :

# logging configuration section
[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = INFO
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stdout,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(asctime)s [%(name)s] %(levelname)-5s: %(message)s
datefmt = %H:%M:%S
