"""create_location_tables

Revision ID: 0abb04009e56
Revises: 407155e53596
Create Date: 2026-06-22 18:40:26.248192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0abb04009e56'
down_revision: Union[str, None] = '407155e53596'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classroom_locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('allowed_radius', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['attendance_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    op.create_index(op.f('ix_classroom_locations_id'), 'classroom_locations', ['id'], unique=False)
    op.create_table('location_validations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.Column('distance_from_center', sa.Float(), nullable=True),
    sa.Column('is_within_radius', sa.Boolean(), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['attendance_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_location_validations_created_at'), 'location_validations', ['created_at'], unique=False)
    op.create_index(op.f('ix_location_validations_id'), 'location_validations', ['id'], unique=False)
    op.create_index(op.f('ix_location_validations_session_id'), 'location_validations', ['session_id'], unique=False)
    op.create_index(op.f('ix_location_validations_student_id'), 'location_validations', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_location_validations_student_id'), table_name='location_validations')
    op.drop_index(op.f('ix_location_validations_session_id'), table_name='location_validations')
    op.drop_index(op.f('ix_location_validations_id'), table_name='location_validations')
    op.drop_index(op.f('ix_location_validations_created_at'), table_name='location_validations')
    op.drop_table('location_validations')
    op.drop_index(op.f('ix_classroom_locations_id'), table_name='classroom_locations')
    op.drop_table('classroom_locations')
    # ### end Alembic commands ###
