"""add_attendance_evidence_table

Revision ID: 0e488c901357
Revises: 993b5d4080df
Create Date: 2026-06-22 19:25:32.483538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e488c901357'
down_revision: Union[str, None] = '993b5d4080df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendance_evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=1024), nullable=False),
    sa.Column('image_public_id', sa.String(length=512), nullable=False),
    sa.Column('image_size', sa.Integer(), nullable=True),
    sa.Column('image_width', sa.Integer(), nullable=True),
    sa.Column('image_height', sa.Integer(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['attendance_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attendance_evidence_id'), 'attendance_evidence', ['id'], unique=False)
    op.create_index(op.f('ix_attendance_evidence_session_id'), 'attendance_evidence', ['session_id'], unique=False)
    op.create_index(op.f('ix_attendance_evidence_student_id'), 'attendance_evidence', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attendance_evidence_student_id'), table_name='attendance_evidence')
    op.drop_index(op.f('ix_attendance_evidence_session_id'), table_name='attendance_evidence')
    op.drop_index(op.f('ix_attendance_evidence_id'), table_name='attendance_evidence')
    op.drop_table('attendance_evidence')
    # ### end Alembic commands ###
