"""create session tokens table

Revision ID: 407155e53596
Revises: beb1a256283e
Create Date: 2026-06-22 18:12:14.044020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '407155e53596'
down_revision: Union[str, None] = 'beb1a256283e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['attendance_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_tokens_expires_at'), 'session_tokens', ['expires_at'], unique=False)
    op.create_index(op.f('ix_session_tokens_id'), 'session_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_session_tokens_token'), 'session_tokens', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_session_tokens_token'), table_name='session_tokens')
    op.drop_index(op.f('ix_session_tokens_id'), table_name='session_tokens')
    op.drop_index(op.f('ix_session_tokens_expires_at'), table_name='session_tokens')
    op.drop_table('session_tokens')
    # ### end Alembic commands ###
