"""add_verification_sessions_table

Revision ID: 993b5d4080df
Revises: 0abb04009e56
Create Date: 2026-06-22 19:07:35.648955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '993b5d4080df'
down_revision: Union[str, None] = '0abb04009e56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('verification_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('camera_granted', sa.Boolean(), nullable=False),
    sa.Column('face_detected', sa.Boolean(), nullable=False),
    sa.Column('blink_verified', sa.Boolean(), nullable=False),
    sa.Column('smile_verified', sa.Boolean(), nullable=False),
    sa.Column('liveness_passed', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['attendance_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verification_sessions_id'), 'verification_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_verification_sessions_session_id'), 'verification_sessions', ['session_id'], unique=False)
    op.create_index(op.f('ix_verification_sessions_status'), 'verification_sessions', ['status'], unique=False)
    op.create_index(op.f('ix_verification_sessions_student_id'), 'verification_sessions', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_verification_sessions_student_id'), table_name='verification_sessions')
    op.drop_index(op.f('ix_verification_sessions_status'), table_name='verification_sessions')
    op.drop_index(op.f('ix_verification_sessions_session_id'), table_name='verification_sessions')
    op.drop_index(op.f('ix_verification_sessions_id'), table_name='verification_sessions')
    op.drop_table('verification_sessions')
    # ### end Alembic commands ###
